---
title: "Data Import and Cleaning"
author: "Deja Simon"
date: "3/10/2021"
output: html_document
---
```{r packages}
library(tidyverse)
library(data.table)
require(car)
library(reshape2)
library(VGAM)
library(psych)
library(lsr)
library(effsize)
library(fmsb)
library(sjstats)
library(frequency)
library(lm.beta)
library(afex)
library(nlme)
library(Rmisc)
library(emmeans)
library(here)
```

```{r loading data}
data <- read_csv(here("data_raw", "GIRA2_raw.csv"))

# removing headings
data <- data %>% slice(3:n())
```

```{r data quality checks}
# Botcha, Attention, and Completion
data <- data %>% filter(botcha1 == "The moon is made of green cheese", botcha2 == "1", attCheck == "3", 'Unique ID' != "")

```

```{r SDO scale cleaning}
# recoding reverse items
data$SDO1 <- revalue(data$SDO1, c("7"="1", "6"="2", "5"="3", "4"="4", "3"="5", "2"="6", "1"="7"))
data$SDO2 <- revalue(data$SDO2, c("7"="1", "6"="2", "5"="3", "4"="4", "3"="5", "2"="6", "1"="7"))
data$SDO3 <- revalue(data$SDO3, c("7"="1", "6"="2", "5"="3", "4"="4", "3"="5", "2"="6", "1"="7"))
data$SDO4 <- revalue(data$SDO4, c("7"="1", "6"="2", "5"="3", "4"="4", "3"="5", "2"="6", "1"="7"))
data$SDO5 <- revalue(data$SDO5, c("7"="1", "6"="2", "5"="3", "4"="4", "3"="5", "2"="6", "1"="7"))
data$SDO6 <- revalue(data$SDO6, c("7"="1", "6"="2", "5"="3", "4"="4", "3"="5", "2"="6", "1"="7"))
data$SDO7 <- revalue(data$SDO7, c("7"="1", "6"="2", "5"="3", "4"="4", "3"="5", "2"="6", "1"="7"))
data$SDO8 <- revalue(data$SDO8, c("7"="1", "6"="2", "5"="3", "4"="4", "3"="5", "2"="6", "1"="7"))


# making all the items numeric
data$SDO1 <- as.numeric(as.character(data$SDO1))
data$SDO2 <- as.numeric(as.character(data$SDO2)) 
data$SDO3 <- as.numeric(as.character(data$SDO3)) 
data$SDO4 <- as.numeric(as.character(data$SDO4)) 
data$SDO5 <- as.numeric(as.character(data$SDO5))
data$SDO6 <- as.numeric(as.character(data$SDO6))
data$SDO7 <- as.numeric(as.character(data$SDO7))
data$SDO8 <- as.numeric(as.character(data$SDO8))
data$SDO9 <- as.numeric(as.character(data$SDO9))
data$SDO10 <- as.numeric(as.character(data$SDO10))
data$SDO11 <- as.numeric(as.character(data$SDO11))
data$SDO12 <- as.numeric(as.character(data$SDO12))
data$SDO13 <- as.numeric(as.character(data$SDO13))
data$SDO14 <- as.numeric(as.character(data$SDO14))
data$SDO15 <- as.numeric(as.character(data$SDO15))
data$SDO16 <- as.numeric(as.character(data$SDO16))


# making a composite variable
attach(data)
data$SDOtotal <- (SDO1 + SDO2 + SDO3 + SDO4 + SDO5 + SDO6 + SDO7 + SDO8 + SDO9 + SDO10 + SDO11 + SDO12 + SDO13 + SDO14 + SDO15 + SDO16)

detach(data)
```

```{r SDO descriptives and reliability}
head(data$SDOtotal)

describe(data$SDOtotal)
boxplot(data$SDOtotal)


# getting the reliability of the scale
names(data)

summary(alpha(as.matrix(data[c(605:620)]), check.keys = FALSE))
```