---
title: "Data Analysis"
author: "Deja Simon"
date: "3/10/2021"
output: html_document
---
```{r analysis functions}
tTest <- function(group1, group2){
  t.test(group1,
       group2,
       paired=TRUE,
       conf.level=0.95)
}

cohenD <- function(group1, group2){
  cohen.d(group1,
       group2,
       paired=TRUE,
       conf.level=0.95)
}
```

```{r signal detection analyses - all data}
cf <- black

cf$correct_white <- cf$White_hits + cf$White_crs
cf$correct_black <- cf$Black_hits + cf$Black_crs
cf$correct_latinx <- cf$Latinx_hits + cf$Latinx_crs

# number correct analysis (total sample)
describe(cf[,c("correct_white","correct_black", "correct_latinx")])

attach(cf)
# White vs. Black
tTest(correct_white, correct_black)
cohenD(correct_white, correct_black)

# White vs. Latinx
tTest(correct_white, correct_latinx)
cohenD(correct_white, correct_latinx)

# Black vs. Latinx
tTest(correct_black, correct_latinx)
cohenD(correct_black, correct_latinx)
detach(cf)

describe(cf[,c("White_hits", "White_crs", "White_fas", "White_misses",
               "Black_hits", "Black_crs", "Black_fas", "Black_misses", "Latinx_hits", "Latinx_crs", "Latinx_fas", "Latinx_misses")])


#36 is the max possible number of responses in each category.
#36 hits would mean all right. 36 false alarms would be all wrong.
#So the total (36x8=288) is double the total number of trials

cf$white_hits <- cf$White_hits/36
cf$white_cr <- cf$White_crs/36
cf$white_fa <- cf$White_fas/36
cf$white_miss <- cf$White_misses/36
cf$black_hits <- cf$Black_hits/36
cf$black_cr <- cf$Black_crs/36
cf$black_fa <- cf$Black_fas/36
cf$black_miss <- cf$Black_misses/36
cf$latinx_hits <- cf$Latinx_hits/36
cf$latinx_cr <- cf$Latinx_crs/36
cf$latinx_fa <- cf$Latinx_fas/36
cf$latinx_miss <- cf$Latinx_misses/36

describe(cf[,c("white_hits","black_hits", "latinx_hits", "white_cr","black_cr", "latinx_cr", "white_fa","black_fa", "latinx_fa", "white_miss","black_miss", "latinx_miss")])


#replacing 1s and 0s for signal detection analysis
#specifically, 0 becomes one-half of an error (.5/72 = .006944) on the bottom end
#and 1 becomes one-half of an error (71.5/72 = .993056) on the top end

cf$white_hits <- ifelse(cf$white_hits==1, .993056, ifelse(cf$white_hits==0, .006944, cf$white_hits))
cf$white_fa <- ifelse(cf$white_fa==1, .993056, ifelse(cf$white_fa==0, .006944, cf$white_fa))
cf$black_hits <- ifelse(cf$black_hits==1, .993056, ifelse(cf$black_hits==0, .006944, cf$black_hits))
cf$black_fa <- ifelse(cf$black_fa==1, .993056, ifelse(cf$black_fa==0, .006944, cf$black_fa))
cf$latinx_hits <- ifelse(cf$latinx_hits==1, .993056, ifelse(cf$latinx_hits==0, .006944, cf$latinx_hits))
cf$latinx_fa <- ifelse(cf$latinx_fa==1, .993056, ifelse(cf$latinx_fa==0, .006944, cf$latinx_fa))

# d' = sensitivity. differentiating between old and new white/black faces.

# c = criterion. predisposition to respond old versus new. Higher values = more signal required to say "yes, seen before"

cf$whiteD <- probit(cf$white_hits) - probit(cf$white_fa)
cf$blackD<- probit(cf$black_hits) - probit(cf$black_fa)
cf$latinxD<- probit(cf$latinx_hits) - probit(cf$latinx_fa)
cf$whiteC<- -(probit(cf$white_hits) + probit(cf$white_fa))/2
cf$blackC<- -(probit(cf$black_hits) + probit(cf$black_fa))/2
cf$latinxC<- -(probit(cf$latinx_hits) + probit(cf$latinx_fa))/2

describe(cf[,c("whiteD", "blackD", "latinxD", "whiteC", "blackC", "latinxC")])

# d' analysis

attach(cf)
# White vs. Black
tTest(whiteD, blackD)
cohenD(whiteD, blackD)
cor.test(whiteD, blackD)

# White vs. Latinx
tTest(whiteD, latinxD)
cohenD(whiteD, latinxD)
cor.test(whiteD, latinxD)

# Black vs. Latinx
tTest(blackD, latinxD)
cohenD(blackD, latinxD)
cor.test(blackD, latinxD)


# c analysis

# White vs. Black
tTest(whiteC, blackC)
cohenD(whiteC, blackC)
cor.test(whiteC, blackC)

# White vs. Latinx
tTest(whiteC, latinxC)
cohenD(whiteC, latinxC)
cor.test(whiteC, latinxC)

# Black vs. Latinx
tTest(blackC, latinxC)
cohenD(blackC, latinxC)
cor.test(blackC, latinxC)
```

```{r graphing - all data}
# selecting needed variables for long data
cf.long <- cf %>% select("ResponseID", "whiteD", "blackD", "latinxD", "whiteC", "blackC", "latinxC")

# long data for d'
d.long <- pivot_longer(cf.long, cols = c("blackD", "whiteD", "latinxD"), names_to = "groupType", values_to = "d'")

# needed values for graphing
d.Summ <- summarySE(d.long, measurevar = "d'", groupvars = c("groupType"), .95)

# d' graph
ggplot(d.Summ, aes(x = groupType, y = `d'`)) + geom_bar(stat = "identity", position = position_dodge()) + labs(title = "d' - All Stimuli") + xlab("Stimuli Race") + scale_x_discrete(labels = c("Black", "Latinx", "White")) + geom_errorbar(aes(ymin = `d'`-se, ymax = `d'`+se), position = position_dodge2(width = .9, padding = .7), alpha = .75) + theme_classic()


# long data for c
c.long <- pivot_longer(cf.long, cols = c("blackC", "whiteC", "latinxC"), names_to = "groupType", values_to = "c")

# needed values for graphing
c.Summ <- summarySE(c.long, measurevar = "c", groupvars = c("groupType"), .95)

# c graph
ggplot(c.Summ, aes(x = groupType, y = c)) + geom_bar(stat = "identity", position = position_dodge()) + labs(title = "c - All Stimuli") + xlab("Stimuli Race") + scale_x_discrete(labels = c("Black", "Latinx", "White")) + geom_errorbar(aes(ymin = c-se, ymax = c+se), position = position_dodge2(width = .9, padding = .7), alpha = .75) + theme_classic()
```

```{r signal detection analyses and graphing - F stim}
cf.femstim <- cf %>% filter(stimGender == "female")

describe(cf.femstim[,c("whiteD", "blackD", "latinxD", "whiteC", "blackC", "latinxC")])

# d' analysis

cf.femstim$D.whitestim <- cf.femstim$whiteD
cf.femstim$C.whitestim<-cf.femstim$whiteC
cf.femstim$D.blackstim<-cf.femstim$blackD
cf.femstim$C.blackstim<-cf.femstim$blackC
cf.femstim$D.latinxstim <- cf.femstim$latinxD
cf.femstim$C.latinxstim <- cf.femstim$latinxC

cf.femstim.long <- cf.femstim %>% select("ResponseID", "D.whitestim", "D.blackstim", "C.whitestim", "C.blackstim", "D.latinxstim", "C.latinxstim")

#"times" refers to stimulus type
cf.femstim.long <- reshape(cf.femstim.long, varying=2:7, times=c("whitestim", "blackstim", "latinxstim"), direction="long")

cf.femstim.long$time<-as.factor(cf.femstim.long$time)
cf.femstim.long$id<-as.factor(cf.femstim.long$id)

d_fem_anova <- aov(D~ time + Error(id/time), cf.femstim.long)
anova_stats(d_fem_anova)

# effect of time (stimuli race)
d.fem.time.means <- emmeans(d_fem_anova, ~ time)
pairs(d.fem.time.means)

describe(cf.femstim$whiteD)
describe(cf.femstim$latinxD)
describe(cf.femstim$blackD)

c_fem_anova <- aov(C~ time + Error(id/time), cf.femstim.long)
anova_stats(c_fem_anova)

# effect of time (stimuli race)
c.fem.time.means <- emmeans(c_fem_anova, ~ time)
pairs(c.fem.time.means)

describe(cf.femstim$whiteC)
describe(cf.femstim$latinxC)
describe(cf.femstim$blackC)
```

```{r signal detection analyses and graphing - M stim}
cf.malestim <- cf %>% filter(stimGender == "male")

describe(cf.malestim[,c("whiteD", "blackD", "latinxD", "whiteC", "blackC", "latinxC")])

# d' analysis

cf.malestim$D.whitestim <- cf.malestim$whiteD
cf.malestim$C.whitestim<-cf.malestim$whiteC
cf.malestim$D.blackstim<-cf.malestim$blackD
cf.malestim$C.blackstim<-cf.malestim$blackC
cf.malestim$D.latinxstim <- cf.malestim$latinxD
cf.malestim$C.latinxstim <- cf.malestim$latinxC

cf.malestim.long <- cf.malestim %>% select("ResponseID", "D.whitestim", "D.blackstim", "C.whitestim", "C.blackstim", "D.latinxstim", "C.latinxstim")

#"times" refers to stimulus type
cf.malestim.long <- reshape(cf.malestim.long, varying=2:7, times=c("whitestim", "blackstim", "latinxstim"), direction="long")

cf.malestim.long$time<-as.factor(cf.malestim.long$time)
cf.malestim.long$id<-as.factor(cf.malestim.long$id)

d_male_anova <- aov(D~ time + Error(id/time), cf.malestim.long)
anova_stats(d_male_anova)

# effect of time (stimuli race)
d.male.time.means <- emmeans(d_male_anova, ~ time)
pairs(d.male.time.means)

describe(cf.malestim$whiteD)
describe(cf.malestim$latinxD)
describe(cf.malestim$blackD)
```

```{r primary analyses}
cf$D.whitestim <- cf$whiteD
cf$C.whitestim<-cf$whiteC
cf$D.blackstim<-cf$blackD
cf$C.blackstim<-cf$blackC
cf$D.latinxstim <- cf$latinxD
cf$C.latinxstim <- cf$latinxC

cf <- cf %>% mutate(SDO_cat = ifelse(SDO_total == min(SDO_total), "low", ifelse(SDO_total >= mean(SDO_total)+sd(SDO_total), "high", "avg")))      

cf.long <- cf %>% select("ResponseId", "D.whitestim", "D.blackstim", "C.whitestim", "C.blackstim", "D.latinxstim", "C.latinxstim", "stimGender", "SDO_cat", "SDO_total")

#"times" refers to stimulus type
cf.long <- reshape(cf.long, varying=2:7, times=c("whitestim", "blackstim", "latinxstim"), direction="long")

str(cf.long)

cf.long$stimGender <- as.factor(cf.long$stimGender)
cf.long$time<-as.factor(cf.long$time)
cf.long$id<-as.factor(cf.long$id)
cf.long$SDO_cat <- as.factor(cf.long$SDO_cat)
cf.long$SDO_total <- as.numeric(cf.long$SDO_total)

d_anova <- aov(D~ time*stimGender*SDO_cat + Error(id/time), cf.long)
anova_stats(d_anova)

# main effect of time (stimuli race)
d.time.means <- emmeans(d_anova, ~ time)
pairs(d.time.means)
# d' is sig. higher for White vs. Black and White vs. Latinx
# d' for Black is higher than Latinx at p = .06

describe(cf$blackD)
describe(cf$whiteD)
describe(cf$latinxD)

# main effect of SDO
d.SDO.means <- emmeans(d_anova, ~ SDO_cat)
pairs(d.SDO.means)
# d' is sig. higher for those high in SDO vs. avg

describeBy(cf.long$D, group = cf.long$SDO_cat)

# interaction of stimGender x SDO
d.genSDO.means <- emmeans(d_anova, ~ stimGender|SDO_cat)
pairs(d.genSDO.means)
# d' is higher for male stim than female stim among low SDO Ss (p = .06)

lowSDO <- cf.long %>% filter(cf.long$SDO_cat == "low")
describeBy(lowSDO$D, group = lowSDO$stimGender)

d.Summ <- summarySE(cf.long, measurevar = "D", groupvars = c("stimGender", "time"), .95)

ggplot(d.Summ, aes(x = time, y = D, fill = stimGender)) + geom_bar(stat = "identity", position = position_dodge()) + labs(x = "Stimuli Race", y = "d'", fill = "Stimuli Gender") + scale_fill_discrete(labels = c("Female", "Male")) + scale_x_discrete(labels = c("Black", "Latinx", "White")) + geom_errorbar(aes(ymin = D-se, ymax = D+se), position = position_dodge2(width = .9, padding = .7), alpha = .75) + theme_classic()




### analysis for C ###

c_anova <- aov(C~ time*stimGender*SDO_cat + Error(id/time), cf.long)
anova_stats(c_anova)

# main effect of time (stimuli race)
c.time.means <- emmeans(c_anova, ~ time)
pairs(c.time.means)

describe(cf$blackC)
describe(cf$whiteC)
describe(cf$latinxC)

c.timeGen.means <- emmeans(c_anova, ~ stimGender|time)
pairs(c.timeGen.means)

# Ms and SDs
whiteStim <- cf.long %>% filter(cf.long$time == "whitestim")
describeBy(whiteStim$C, group = whiteStim$stimGender)

blackStim <- cf.long %>% filter(cf.long$time == "blackstim")
describeBy(blackStim$C, group = blackStim$stimGender)

latinxStim <- cf.long %>% filter(cf.long$time == "latinxstim")
describeBy(latinxStim$C, group = latinxStim$stimGender)

c.Summ <- summarySE(cf.long, measurevar = "C", groupvars = c("stimGender", "time"), .95)

ggplot(c.Summ, aes(x = time, y = C, fill = stimGender)) + geom_bar(stat = "identity", position = position_dodge()) + labs(x = "Stimuli Race", y = "c", fill = "Stimuli Gender") + scale_fill_discrete(labels = c("Female", "Male")) + scale_x_discrete(labels = c("Black", "Latinx", "White")) + geom_errorbar(aes(ymin = C-se, ymax = C+se), position = position_dodge2(width = .9, padding = .7), alpha = .75) + theme_classic()
```

```{r correlations}
attach(cf)

# d'
cor.test(SDO_total, whiteD)
cor.test(SDO_total, blackD)
cor.test(SDO_total, latinxD)

cf$bwDdiff <- blackD - whiteD
cor.test(cf$bwDdiff, SDO_total)

cf$blDdiff <- blackD - latinxD
cor.test(cf$blDdiff, SDO_total)

cf$wlDdiff <- whiteD - latinxD
cor.test(cf$wlDdiff, SDO_total)


# c
cor.test(SDO_total, whiteC)
cor.test(SDO_total, blackC)
cor.test(SDO_total, latinxC)

cf$bwCdiff <- blackC - whiteC
cor.test(cf$bwCdiff, SDO_total)

cf$blCdiff <- blackC - latinxC
cor.test(cf$blCdiff, SDO_total)

cf$wlCdiff <- whiteC - latinxC
cor.test(cf$wlCdiff, SDO_total)

detach(cf)
```

```{r location analysis}
setwd("~/Desktop")

# loading and cleaning data
location1 <- read.csv("Study 2 IP spreadsheet pt 1.csv")
location2 <- read.csv("Study 2 IP spreadsheet pt 2.csv")
location2 <- location2 %>% select(-("X"))

location1$censusGroup <- tolower(location1$censusGroup)
location1$censusGroup[location1$censusGroup == "cdp"] <- "CDP"

locationDat <- rbind(location1, location2)

newDat <- cbind(cf, locationDat)
newDat <- na.omit(newDat)


# turning wide data into long
newDat.long <- newDat %>% select("race", "D.whitestim", "D.blackstim", "C.whitestim", "C.blackstim", "D.latinxstim", "C.latinxstim", "participant", "percentWhite", "percentBlack")

newDat.long <- reshape(newDat.long, varying=2:7, times=c("whitestim", "blackstim", "latinxstim"), direction="long")

newDat.long$time <- factor(newDat.long$time, levels = c("whitestim", "blackstim", "latinxstim"))

# percentBlack analysis
dReg <- lm(D ~ time*percentBlack, data = newDat.long)
summary(dReg)

cReg <- lm(C ~ time*percentBlack, data = newDat.long)
summary(cReg)


# Difference score analysis
newDat$diffScore <- newDat$percentWhite - newDat$percentBlack

newDat.long2 <- newDat %>% select("race", "D.whitestim", "D.blackstim", "C.whitestim", "C.blackstim", "D.latinxstim", "C.latinxstim", "participant", "percentWhite", "percentBlack", "diffScore")

newDat.long2 <- reshape(newDat.long2, varying=2:7, times=c("whitestim", "blackstim", "latinxstim"), direction="long")

newDat.long2$time <- factor(newDat.long2$time, levels = c("whitestim", "blackstim", "latinxstim"))


dReg2 <- lm(D ~ time*diffScore, data = newDat.long2)
summary(dReg2)

cReg2 <- lm(C ~ time*diffScore, data = newDat.long2)
summary(cReg2)
```
