---
title: "Data Transformation"
author: "Deja Simon"
date: "3/10/2021"
output: html_document
---

```{r split half reliability of recog phase}
# Female stimuli
data.recog.f <- select(data, starts_with("RWF"), starts_with("RBF"), starts_with("RLF"))
data.recog.f <- data.recog.f %>% filter(RWF01 != "")
data.recog.f <- mutate_all(data.recog.f, function(x) as.numeric(as.character(x)))

score.e.f <- rowMeans(data.recog.f[, c(TRUE, FALSE)])
score.o.f <- rowMeans(data.recog.f[, c(FALSE, TRUE)])

r.f <- cor(score.e.f, score.o.f)

# Split half formula
(2*r.f) / (1 + r.f)


# Male stimuli
data.recog.m <- select(data, starts_with("RWM"), starts_with("RBM"), starts_with("RLM"))
data.recog.m <- data.recog.m %>% filter(RWM01 != "")
data.recog.m <- mutate_all(data.recog.m, function(x) as.numeric(as.character(x)))

score.e.m <- rowMeans(data.recog.m[, c(TRUE, FALSE)])
score.o.m <- rowMeans(data.recog.m[, c(FALSE, TRUE)])

r.m <- cor(score.e.m, score.o.m)

# Split half formula
(2*r.m) / (1 + r.m)
```

```{r parsing raw data into correct/incorrect - F stim}
data.femstim <- data %>% filter(RWF01 != "")

# Learning Phase

# X = White
# Y = Latinx
# Z = Black  

# Female Stimuli
learn.XF <- select(data.femstim, matches("ResponseId"), matches("Page.Submit"), -starts_with("YF"), -starts_with("ZF"), -starts_with("RXF"), -starts_with("RYF"), -starts_with("RZF"), -starts_with("RWF"),-starts_with("RLF"),-starts_with("RBF"), -starts_with("XM"), -starts_with("YM"), -starts_with("ZM"), -starts_with("RXM"), -starts_with("RYM"), -starts_with("RZM"), -starts_with("RWM"),-starts_with("RLM"),-starts_with("RBM"))

learn.YF <- select(data.femstim, matches("ResponseId"), matches("Page.Submit"), -starts_with("XF"), -starts_with("ZF"), -starts_with("RXF"), -starts_with("RYF"), -starts_with("RZF"), -starts_with("RWF"),-starts_with("RLF"),-starts_with("RBF"), -starts_with("XM"), -starts_with("YM"), -starts_with("ZM"), -starts_with("RXM"), -starts_with("RYM"), -starts_with("RZM"), -starts_with("RWM"),-starts_with("RLM"),-starts_with("RBM"))

learn.ZF <- select(data.femstim, matches("ResponseId"), matches("Page.Submit"), -starts_with("XF"), -starts_with("YF"), -starts_with("RXF"), -starts_with("RYF"), -starts_with("RZF"), -starts_with("RWF"),-starts_with("RLF"),-starts_with("RBF"), -starts_with("XM"), -starts_with("YM"), -starts_with("ZM"), -starts_with("RXM"), -starts_with("RYM"), -starts_with("RZM"), -starts_with("RWM"),-starts_with("RLM"),-starts_with("RBM"))

fem.learn <- cbind(learn.XF, learn.YF, learn.ZF)

fem.learn <- fem.learn[!duplicated(as.list(fem.learn))]

fem.learn.phase <- fem.learn %>%
  gather(matches("Page.submit"),key = "Stimuli Race", value = "Response")


# Recognition Phase 
fem.test <- select(data.femstim, matches("ResponseId"), starts_with("RWF"), starts_with("RLF"), starts_with("RBF"), -starts_with("RXF"), -starts_with("RYF"), -starts_with("RZF"), -starts_with("RXM"), -starts_with("RYM"), -starts_with("RZM"),-ends_with("Last.Click"), -ends_with("Click.Count"), -ends_with("Page.Submit"), -ends_with("First.Click"))

fem.test.phase <- fem.test %>%
  gather(starts_with("RW"), starts_with("RL"), starts_with("RB"), key = "Test", value = "res")


# combining learning and recognition
fem.dup.cf <- cbind(fem.learn.phase, fem.test.phase)


# removing duplicate Response ID column
fem.cf.nodup <- fem.dup.cf[!duplicated(as.list(fem.dup.cf))]

fem.cf.nodup <- as.data.frame(fem.cf.nodup)

fem.cf.nodup[is.na(fem.cf.nodup)] <- 0


# Coding correct vs. incorrect

# 1 = yes, seen  
# 2 = no, not seen 

fem.cfBasic <- fem.cf.nodup %>% mutate(Correct = case_when(Response != "" & res == "1" | res == "Yes" ~ 1, Response == "" & res == "2" | res == "No" ~ 2, TRUE ~ 0),
                          Incorrect = case_when(Response == "" & res == "1" | res == "Yes" ~ 1, Response != "" & res == "2" | res == "No" ~ 2, TRUE ~ 0))


fem.cfBasic$Type <- ifelse(grepl("X", fem.cfBasic$`Stimuli Race`, ignore.case = T), "White",
                  ifelse(grepl("Z", fem.cfBasic$`Stimuli Race`, ignore.case = T), "Black", "Latinx"))


# rearranging columns
fem.cfBasic <- fem.cfBasic %>% select(ResponseId, `Stimuli Race`, Type, Response, Test, res, Correct, Incorrect)
```

```{r parsing raw data into correct/incorrect - M stim}
data.malestim <- data %>% filter(RWM01 != "")

# Learning Phase

# X = White
# Y = Latinx
# Z = Black  

# Male Stimuli
learn.XM <- select(data.malestim, matches("ResponseId"), matches("Page.Submit"), -starts_with("YM"), -starts_with("ZM"), -starts_with("RXM"), -starts_with("RYM"), -starts_with("RZM"), -starts_with("RWM"),-starts_with("RLM"),-starts_with("RBM"), -starts_with("XF"), -starts_with("YF"), -starts_with("ZF"), -starts_with("RXF"), -starts_with("RYF"), -starts_with("RZF"), -starts_with("RWF"),-starts_with("RLF"),-starts_with("RBF"))

learn.YM <- select(data.malestim, matches("ResponseId"), matches("Page.Submit"), -starts_with("XM"), -starts_with("ZM"), -starts_with("RXM"), -starts_with("RYM"), -starts_with("RZM"), -starts_with("RWM"),-starts_with("RLM"),-starts_with("RBM"), -starts_with("XF"), -starts_with("YF"), -starts_with("ZF"), -starts_with("RXF"), -starts_with("RYF"), -starts_with("RZF"), -starts_with("RWF"),-starts_with("RLF"),-starts_with("RBF"))

learn.ZM <- select(data.malestim, matches("ResponseId"), matches("Page.Submit"), -starts_with("XM"), -starts_with("YM"), -starts_with("RXM"), -starts_with("RYM"), -starts_with("RZM"), -starts_with("RWM"),-starts_with("RLM"),-starts_with("RBM"), -starts_with("XF"), -starts_with("YF"), -starts_with("ZF"), -starts_with("RXF"), -starts_with("RYF"), -starts_with("RZF"), -starts_with("RWF"),-starts_with("RLF"),-starts_with("RBF"))

male.learn <- cbind(learn.XM, learn.YM, learn.ZM)

male.learn <- male.learn[!duplicated(as.list(male.learn))]

male.learn.phase <- male.learn %>%
  gather(matches("Page.submit"),key = "Stimuli Race", value = "Response")


# Recognition Phase 
male.test <- select(data.malestim, matches("ResponseId"), starts_with("RWM"), starts_with("RLM"), starts_with("RBM"), -starts_with("RXM"), -starts_with("RYM"), -starts_with("RZM"), -starts_with("RXF"), -starts_with("RYF"), -starts_with("RZF"),-ends_with("Last.Click"), -ends_with("Click.Count"), -ends_with("Page.Submit"), -ends_with("First.Click"))

male.test.phase <- male.test %>%
  gather(starts_with("RW"), starts_with("RL"), starts_with("RB"), key = "Test", value = "res")


# combining learning and recognition
male.dup.cf <- cbind(male.learn.phase, male.test.phase)


# removing duplicate Response ID column
male.cf.nodup <- male.dup.cf[!duplicated(as.list(male.dup.cf))]

male.cf.nodup <- as.data.frame(male.cf.nodup)

male.cf.nodup[is.na(male.cf.nodup)] <- 0


# Coding correct vs. incorrect

# 1 = yes, seen  
# 2 = no, not seen 

male.cfBasic <- male.cf.nodup %>% mutate(Correct = case_when(Response != "" & res == "1" | res == "Yes" ~ 1, Response == "" & res == "2" | res == "No" ~ 2, TRUE ~ 0),
                          Incorrect = case_when(Response == "" & res == "1" | res == "Yes" ~ 1, Response != "" & res == "2" | res == "No" ~ 2, TRUE ~ 0))


male.cfBasic$Type <- ifelse(grepl("X", male.cfBasic$`Stimuli Race`, ignore.case = T), "White",
                  ifelse(grepl("Z", male.cfBasic$`Stimuli Race`, ignore.case = T), "Black", "Latinx"))


# rearranging columns
male.cfBasic <- male.cfBasic %>% select(ResponseId, `Stimuli Race`, Type, Response, Test, res, Correct, Incorrect)
```

```{r}
num_of_hits_white <- fem.cfBasic %>% group_by(ResponseId) %>% mutate(hits_white = case_when(Correct == '1' & Type == "White" ~ 1, TRUE ~ 0)) %>% tally(hits_white)

answer_array <- c("Correct", "Incorrect")
cor_array <- c("1", "2")
type_array <- c("White", "Black", "Latinx")

for(k in answer_array){
for(i in cor_array) {
  for (j in type_array) {
    if(k == "Correct" & i == "1") {
      label <- "hits"
    } else if(k == "Correct" & i == "2") {
      label <- "cr"
    } else if(k == "Incorrect" & i == "1") {
      label <- "fa"
    } else if(k == "Incorrect" & i == "2") {
      label <- "miss"
    }
    name <- paste0("num_of_", label, "_",j)
    if(k == "Correct") {
    curr_file <- fem.cfBasic %>% group_by(ResponseId) %>%   mutate(hits_white = case_when(Correct == i & Type == j ~ 1, TRUE ~ 0)) %>% tally(hits_white)
    } else if(k == "Incorrect") {
    curr_file <- fem.cfBasic %>% group_by(ResponseId) %>%   mutate(hits_white = case_when(Incorrect == i & Type == j ~ 1, TRUE ~ 0)) %>% tally(hits_white)
    }
  }
}
}
```

```{r}
sigDet <- function(data, type) {
num_of_hits_ <- data %>% group_by(ResponseId) %>% mutate(hits_white = case_when(Correct == '1' & Type == type ~ 1, TRUE ~ 0)) %>% tally(hits_white) 

label <- paste0("num_of_hits_", type)
file <- assign(label, num_of_hits_)

num_of_cr_ <- data %>% group_by(ResponseId) %>% mutate(cr_white = case_when(Correct == '2' & Type == type ~ 1, TRUE ~ 0)) %>% tally(cr_white) 

num_of_fa_ <- data %>% group_by(ResponseId) %>% mutate(fa_white = case_when(Incorrect == '1' & Type == type ~ 1, TRUE ~ 0)) %>% tally(fa_white) 

num_of_miss_ <- data %>% group_by(ResponseId) %>% mutate(miss_white = case_when(Incorrect == '2' & Type == type ~ 1, TRUE ~ 0)) %>% tally(miss_white) 

cbind(num_of_hits_, num_of_cr_$n, num_of_fa_$n, num_of_miss_$n) %>% set_names("ResponseId", "hits", "crs", "fas", "misses")
}

sigDet(fem.cfBasic, "White")
```

```{r response frequencies - F stim}
# White stimuli
num_of_hits_white <- fem.cfBasic %>% group_by(ResponseId) %>% mutate(hits_white = case_when(Correct == '1' & Type == "White" ~ 1, TRUE ~ 0)) %>% tally(hits_white)

num_of_cr_white <- fem.cfBasic %>% group_by(ResponseId) %>% mutate(cr_white = case_when(Correct == '2' & Type == "White" ~ 1, TRUE ~ 0)) %>% tally(cr_white)

num_of_fa_white <- fem.cfBasic %>% group_by(ResponseId) %>% mutate(fa_white = case_when(Incorrect == '1' & Type == "White" ~ 1, TRUE ~ 0)) %>% tally(fa_white)

num_of_miss_white <- fem.cfBasic %>% group_by(ResponseId) %>% mutate(miss_white = case_when(Incorrect == '2' & Type == "White" ~ 1, TRUE ~ 0)) %>% tally(miss_white)


# Black stimuli
num_of_hits_black <- fem.cfBasic %>% group_by(ResponseId) %>% mutate(hits_black = case_when(Correct == '1' & Type == "Black" ~ 1, TRUE ~ 0)) %>% tally(hits_black)

num_of_cr_black <- fem.cfBasic %>% group_by(ResponseId) %>% mutate(cr_black = case_when(Correct == '2' & Type == "Black" ~ 1, TRUE ~ 0)) %>% tally(cr_black)

num_of_fa_black <- fem.cfBasic %>% group_by(ResponseId) %>% mutate(fa_black = case_when(Incorrect == '1' & Type == "Black" ~ 1, TRUE ~ 0)) %>% tally(fa_black)

num_of_miss_black <- fem.cfBasic %>% group_by(ResponseId) %>% mutate(miss_black = case_when(Incorrect == '2' & Type == "Black" ~ 1, TRUE ~ 0)) %>% tally(miss_black)


# Latinx stimuli
num_of_hits_latinx <- fem.cfBasic %>% group_by(ResponseId) %>% mutate(hits_latinx = case_when(Correct == '1' & Type == "Latinx" ~ 1, TRUE ~ 0)) %>% tally(hits_latinx)

num_of_cr_latinx <- fem.cfBasic %>% group_by(ResponseId) %>% mutate(cr_latinx = case_when(Correct == '2' & Type == "Latinx" ~ 1, TRUE ~ 0)) %>% tally(cr_latinx)

num_of_fa_latinx <- fem.cfBasic %>% group_by(ResponseId) %>% mutate(fa_latinx = case_when(Incorrect == '1' & Type == "Latinx" ~ 1, TRUE ~ 0)) %>% tally(fa_latinx)

num_of_miss_latinx <- fem.cfBasic %>% group_by(ResponseId) %>% mutate(miss_latinx = case_when(Incorrect == '2' & Type == "Latinx" ~ 1, TRUE ~ 0)) %>% tally(miss_latinx)


# new dataframe
f_exp <- cbind(num_of_hits_white, num_of_cr_white, num_of_fa_white, num_of_miss_white,
            num_of_hits_black, num_of_cr_black, num_of_fa_black, num_of_miss_black, num_of_hits_latinx, num_of_cr_latinx, num_of_fa_latinx, num_of_miss_latinx, data.femstim$race, data.femstim$age, data.femstim$IPAddress, data.femstim$gender, data.femstim$SDOtotal)


f_cf_all <- f_exp[!duplicated(as.list(f_exp))]

names(f_cf_all) <- c("ResponseID", "number_of_hits_white",
                   "number_of_cr_white",
                   "number_of_fa_white",
                   "number_of_miss_white",
                   "number_of_hits_black",
                   "number_of_cr_black",
                   "number_of_fa_black",
                   "number_of_miss_black", "number_of_hits_latinx",
                   "number_of_cr_latinx",
                   "number_of_fa_latinx",
                   "number_of_miss_latinx",
                   "race", "age", "ipAddress", "gender", "SDO_total")

attach(f_cf_all)
f_cf_all$total <- number_of_hits_white +
  number_of_cr_white +
  number_of_fa_white +
  number_of_miss_white +
  number_of_hits_black +
  number_of_cr_black +
  number_of_fa_black +
  number_of_miss_black +
  number_of_hits_latinx +
  number_of_cr_latinx +
  number_of_fa_latinx +
  number_of_miss_latinx
# should sum to 144; filtering out people who don't add up to that below

detach(f_cf_all)

f_dat <- f_cf_all %>% filter(total == "144")

f_dat$stimGender <- "female"
```

```{r response frequencies - M stim}
# White stimuli
num_of_hits_white <- male.cfBasic %>% group_by(ResponseId) %>% mutate(hits_white = case_when(Correct == '1' & Type == "White" ~ 1, TRUE ~ 0)) %>% tally(hits_white)

num_of_cr_white <- male.cfBasic %>% group_by(ResponseId) %>% mutate(cr_white = case_when(Correct == '2' & Type == "White" ~ 1, TRUE ~ 0)) %>% tally(cr_white)

num_of_fa_white <- male.cfBasic %>% group_by(ResponseId) %>% mutate(fa_white = case_when(Incorrect == '1' & Type == "White" ~ 1, TRUE ~ 0)) %>% tally(fa_white)

num_of_miss_white <- male.cfBasic %>% group_by(ResponseId) %>% mutate(miss_white = case_when(Incorrect == '2' & Type == "White" ~ 1, TRUE ~ 0)) %>% tally(miss_white)


# Black stimuli
num_of_hits_black <- male.cfBasic %>% group_by(ResponseId) %>% mutate(hits_black = case_when(Correct == '1' & Type == "Black" ~ 1, TRUE ~ 0)) %>% tally(hits_black)

num_of_cr_black <- male.cfBasic %>% group_by(ResponseId) %>% mutate(cr_black = case_when(Correct == '2' & Type == "Black" ~ 1, TRUE ~ 0)) %>% tally(cr_black)

num_of_fa_black <- male.cfBasic %>% group_by(ResponseId) %>% mutate(fa_black = case_when(Incorrect == '1' & Type == "Black" ~ 1, TRUE ~ 0)) %>% tally(fa_black)

num_of_miss_black <- male.cfBasic %>% group_by(ResponseId) %>% mutate(miss_black = case_when(Incorrect == '2' & Type == "Black" ~ 1, TRUE ~ 0)) %>% tally(miss_black)


# Latinx stimuli
num_of_hits_latinx <- male.cfBasic %>% group_by(ResponseId) %>% mutate(hits_latinx = case_when(Correct == '1' & Type == "Latinx" ~ 1, TRUE ~ 0)) %>% tally(hits_latinx)

num_of_cr_latinx <- male.cfBasic %>% group_by(ResponseId) %>% mutate(cr_latinx = case_when(Correct == '2' & Type == "Latinx" ~ 1, TRUE ~ 0)) %>% tally(cr_latinx)

num_of_fa_latinx <- male.cfBasic %>% group_by(ResponseId) %>% mutate(fa_latinx = case_when(Incorrect == '1' & Type == "Latinx" ~ 1, TRUE ~ 0)) %>% tally(fa_latinx)

num_of_miss_latinx <- male.cfBasic %>% group_by(ResponseId) %>% mutate(miss_latinx = case_when(Incorrect == '2' & Type == "Latinx" ~ 1, TRUE ~ 0)) %>% tally(miss_latinx)


# new dataframe
m_exp <- cbind(num_of_hits_white, num_of_cr_white, num_of_fa_white, num_of_miss_white,
            num_of_hits_black, num_of_cr_black, num_of_fa_black, num_of_miss_black, num_of_hits_latinx, num_of_cr_latinx, num_of_fa_latinx, num_of_miss_latinx, data.malestim$race, data.malestim$age, data.malestim$IPAddress, data.malestim$gender, data.malestim$SDOtotal)


m_cf_all <- m_exp[!duplicated(as.list(m_exp))]

names(m_cf_all) <- c("ResponseID", "number_of_hits_white",
                   "number_of_cr_white",
                   "number_of_fa_white",
                   "number_of_miss_white",
                   "number_of_hits_black",
                   "number_of_cr_black",
                   "number_of_fa_black",
                   "number_of_miss_black", "number_of_hits_latinx",
                   "number_of_cr_latinx",
                   "number_of_fa_latinx",
                   "number_of_miss_latinx",
                   "race", "age", "ipAddress", "gender", "SDO_total")

attach(m_cf_all)
m_cf_all$total <- number_of_hits_white +
  number_of_cr_white +
  number_of_fa_white +
  number_of_miss_white +
  number_of_hits_black +
  number_of_cr_black +
  number_of_fa_black +
  number_of_miss_black +
  number_of_hits_latinx +
  number_of_cr_latinx +
  number_of_fa_latinx +
  number_of_miss_latinx
# should sum to 144; filtering out people who don't add up to that below

detach(m_cf_all)

m_dat <- m_cf_all %>% filter(total == "144")

m_dat$stimGender <- "male"

all_dat <- rbind(f_dat, m_dat)
```

```{r final sample descriptives and Ns}
# only Black Ss
black <- all_dat %>% filter(race == "1")

setwd("~/Desktop")
write.csv(black, file = "GIRA2_clean.csv", row.names = FALSE)

# gender: 1 = male, 2 = female, 3 = nonbinary
count(black, vars = "gender")
black$age <- as.numeric(as.character(black$age))
describe(black$age)

count(black, vars = "stimGender")
```